version: '3'
services:
  restaurant-service:
    container_name: restaurant-service
    build:
      context: .
      dockerfile: Dockerfile.restaurant
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      default:
    ports:
      - "8080:8080"
    depends_on:
      - solr
      - kafka

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile.user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      default:
    ports:
      - "8081:8081"
    depends_on:
      - user_db
      - kafka
    restart:
      on-failure

  log-service:
    container_name: log-service
    build:
      context: .
      dockerfile: Dockerfile.log
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      default:
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    restart:
      on-failure

  user_db:
    container_name: user_db
    image: postgres
    environment:
      POSTGRES_DB: bootcamp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    networks:
      default:
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  solr:
    image: solr:latest
    container_name: n11_solr
    networks:
      default:
    ports:
      - "8983:8983"
    volumes:
      - ./restaurant-service/data:/var/solr
    command:
      - solr-precreate
      - n11_restaurants

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper